### ISSUE TITLE
x-message-id

### ISSUE THREAD

**Issue by milannikic-sh** [janjaali/sendGrid-mock#47]
Is it possible to add `x-message-id` to the response header for the POST (/mail/send) endpoint?
Explanation of that field is here: https://docs.sendgrid.com/glossary/what-is-x-message-id

**Comment by janjaali** [comment]
Sure! Guess it is sufficient enought to start with a random UUID as returned `x-message-id` for now. Real uniqueness of returned `x-message-id` or `message-id` is probably out of scope for this mock server project.

**Comment by milannikic-sh** [comment]
Thanks. Of course UUID is sufficient - just to have something in the header under the `x-message-id` key.

**Comment by janjaali** [comment]
Added in <https://github.com/janjaali/sendGrid-mock/releases/tag/v1.8.2> ;)
