### ISSUE TITLE
The API returns 200 even though the JSON is malformed

### ISSUE THREAD

**Issue by JoffreyGermainUpSlide** [janjaali/sendGrid-mock#61]
For example, when providing a JSON payload formed as follow:
```
{
   "from": "test@mycompany.com"
}
```
instead of:
```
{
   "from": {
      "email": "test@mycompany.com",
      "name": "Test"
   }
}
```
This SendGrid Mock will return a 200 response, an email will be stored in the docker image and it will be displayed in the UI with an empty "from" value.

The original SendGrid API however returns a 4XX response.
Would it be possible to mimic their error handling to get a mock as close as possible from the SendGrid API ?

**Comment by janjaali** [comment]
Sure, we can and should fix this. Will check within the next days weeks.
