### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by tr1et** [janjaali/sendGrid-mock#62]
Hi, I see that your [package.json](https://github.com/janjaali/sendGrid-mock/blob/4e1035d6e27164ddfe53781a51214057943957fc/package.json#L29C2-L29C20) state that the project is MIT licensed. But there's no [LICENSE](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) file to be found.

Can you add one to make others easier to use or contribute to your project? Or do you need me to create a pull request?
I didn't create a pull request because sensitive things like LICENSE are better done by the project owner.

**Comment by janjaali** [comment]
I will check and come back to this request.
