### ISSUE TITLE
Sender behavior differs from SendGrid

### ISSUE THREAD

**Issue by JoffreyGermainUpSlide** [janjaali/sendGrid-mock#67]
Hello,

While trying out 1.9.0 I stumbled across the following: SendGrid API accepts some **null** values while the mock doesn't.

For example:
`
"from": {
    "email": "no-reply@my-company.com",
    "name": null
  },
`
is accepted by SendGrid while the Mock complains about "name" not being a string value.

I haven't tested if that may be case for other properties but according to this documentation https://docs.sendgrid.com/api-reference/mail-send/errors, the name is optional in the model. I am using C# to call that API, and the name is nullable in my model, thus the JSON payload created contains null values.

Thanks !

**Comment by janjaali** [comment]
Yes, the name is an optional field. Seems that the library used to verify the JSON is not (or at least not out-of-the-box) considering null values as non-existent. I will have a look.
