### ISSUE TITLE
[Question] - API Key

### ISSUE THREAD

**Issue by alejoFernandezSS** [janjaali/sendGrid-mock#73]
Hey there! Im trying to understand why the mock server needs an actual valid API key. 
I tried using a non valid (but with right format) key and its giving me an authentication error so Im guessing it actually uses it for something.
I want to implement this on my development team but some people are concerned about sending our API Key to 3rd parties. 
Thanks!

**Comment by alejoFernandezSS** [comment]
Nevermind.... I just figured it out 🤦

**Comment by fernandosesma** [comment]
Wondering the same thing, what did you find?

**Comment by alejoFernandezSS** [comment]
Hi @fernandosesma ! Basically the API Key sent to the container needs to be same that you use in your sendgrid client. What I ended up doing was adding a `MOCK_API_KEY` variable to my .env file and when I want to use the docker container I initalize the sengrid client with that key instead of the actual real key. Keep in mind that the key needs to be the correct format, for example I used `SG.123456` and it works just fine

**Comment by fernandosesma** [comment]
> Hi @fernandosesma ! Basically the API Key sent to the container needs to be same that you use in your sendgrid client. What I ended up doing was adding a `MOCK_API_KEY` variable to my .env file and when I want to use the docker container I initalize the sengrid client with that key instead of the actual real key. Keep in mind that the key needs to be the correct format, for example I used `SG.123456` and it works just fine

Ah okay great, thanks for the response! Appreciate it!
