### ISSUE TITLE
SendGrid does not require 'content' field for templated emails

### ISSUE THREAD

**Issue by zopu** [janjaali/sendGrid-mock#74]
When I send our server's (working) sendgrid request (constructed via sendgrid's golang client API) to sendgrid-mock I see the following error:
```
{"errors":[{"field":"content","message":"must have required property 'content'","path":"#/required"}]}
```

Looking at the [RequestHandler source](https://github.com/janjaali/sendGrid-mock/blob/c34185951abd5c8be93c3db2726ba862a4ad824c/src/server/RequestHandler.js#L8):

I see 
```
v3MailSend: {
    type: 'object',
    required: ['personalizations', 'content', 'from', 'subject'],
```

I also noticed that the template example in post-mail-template.http doesn't have a content field. Is this example working?

Apologies if I'm missing something obvious!

**Comment by zopu** [comment]
Here's our request (with a couple of things redacted):
```
 {"from":{"name":"Me","email":"me@example.com"},"personalizations":[{"to":[{"name":"Mike","email":"me@example.com"}],"dynamic_template_data":{"pass_updated_body":"<snip>","pass_updated_subj":"Your password has been updated"}}],"template_id":"<snip>"}
```

**Comment by zopu** [comment]
Same issue with the 'subject' field.

It seems can work around for now by adding {"text/html", ""}, " " as content/subject fields.

PS apart from this issue this is really nice and handy, thanks!

**Comment by janjaali** [comment]
Should be fixed with <https://github.com/janjaali/sendGrid-mock/releases/tag/v1.9.2>. Please feel free to open issue again if not.
